name: mcapibridge
description: A Dart library for controlling Minecraft via MCAPIBridge mod.
version: 1.0.4
repository: https://github.com/TaotianZhufang/MCAPIBridge/tree/main/Bridges/Dart

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
